spring:
  application:
    name: fin-tracker
  datasource:
    url: jdbc:postgresql://localhost:5432/fin-tracker-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080
  servlet:
    context-path: /api
